name: nginx-tf
on: 
  push:
    paths:
    - nginx/**
  pull_request:
    paths:
    - nginx/**

jobs:
  lint:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./nginx
    steps:
    - name: Checkout files
      uses: actions/checkout@v2

    - uses: terraform-linters/setup-tflint@v1
      name: Setup TFLint

    - name: Show version
      run: tflint --version

    - name: Init TFLint
      run: tflint --init

    - name: Run TFLint
      run: tflint -f compact


  